version: '3'
services:
  #Technical Health Dashboard
  thd:
    image: swspgroup2/technical-health-dashboard
    container_name: thd-webapp
    ports:
    - 3000:80
    networks:
    - network-name
    environment:
      OFFLINE_STATUS: 0
      ONLINE_STATUS: 1
      HAS_ERRORS_STATUS: 2
      SERVER_URL: http://localhost
      SERVER_PORT: 6060

  #Technical Health Service Demo
  ths:
    image: swspgroup2/technical-health-service
    container_name: technical-health-service
    ports:
      - 6060:6060
    networks:
      - network-name
    environment:
      OFFLINE_STATUS: 0
      ONLINE_STATUS: 1
      HAS_ERRORS_STATUS: 2
      CLIENT_URL: http://localhost
      CLIENT_PORT: 3000
networks:
  network-name:
    name: swsp
